testing error
Signed-off-by: Ryan Cook <rcook@redhat.com>

diff --git a/.github/workflows/kind-awx.yaml b/.github/workflows/kind-awx.yaml
--- a/.github/workflows/kind-awx.yaml
+++ b/.github/workflows/kind-awx.yaml
@@ -156,6 +156,7 @@ jobs:
           kubectl wait ansiblejob -n awx demo-job --for condition=Successful=True --timeout=60s
           kubectl apply -f config/samples/tower_v1alpha1_ansiblejob-broken.yaml -n awx
           kubectl wait ansiblejob -n awx broke-job --for condition=Successful=True --timeout=60s
+          if [[ $(kubectl get ansiblejob -n awx broke-job -o jsonpath={.status.error_message}) ]]; then echo "Job errored correctly"; else exit 1 ;fi
           
       - name: launch a template
         run: |
