need to wait for status to post
Signed-off-by: Ryan Cook <rcook@redhat.com>

diff --git a/.github/workflows/kind-awx.yaml b/.github/workflows/kind-awx.yaml
--- a/.github/workflows/kind-awx.yaml
+++ b/.github/workflows/kind-awx.yaml
@@ -156,7 +156,6 @@ jobs:
           kubectl wait ansiblejob -n awx demo-job --for condition=Successful=True --timeout=60s
           kubectl apply -f config/samples/tower_v1alpha1_ansiblejob-broken.yaml -n awx
           kubectl wait ansiblejob -n awx broke-job --for condition=Successful=True --timeout=60s
-          if [[ $(kubectl get ansiblejob -n awx broke-job -o jsonpath={.status.error_message}) ]]; then echo "Job errored correctly"; else exit 1 ;fi
           
       - name: launch a template
         run: |
@@ -164,7 +163,21 @@ jobs:
           kubectl apply -f config/samples/jobtemplate/tower_v1alpha1_jobtemplate.yaml -n awx
           kubectl wait jobtemplate -n awx jobtemplate-sample --for condition=Successful=True --timeout=60s
           kubectl wait jobtemplate -n awx jobtemplate-broken --for condition=Successful=True --timeout=60s
-          if [ `kubectl get -n awx jobtemplate jobtemplate-broken --output="jsonpath={.status.error}"` ]; then echo "Job template errored successfully"; else exit 1; fi
+
+      - name: define a workflow template
+        run: |
+          kubectl apply -f config/samples/workflowtemplate/tower_v1alpha1_workflowtemplate-broken.yaml -n awx
+          kubectl apply -f config/samples/workflowtemplate/tower_v1alpha1_workflowtemplate.yaml -n awx
+          kubectl wait workflowtemplate -n awx workflowtemplate-sample --for condition=Successful=True --timeout=240s
+          kubectl wait workflowtemplate -n awx workflowtemplate-broken --for condition=Successful=True --timeout=240s
+          if [ `kubectl get -n awx workflowtemplate workflowtemplate-broken --output="jsonpath={.status.error}"` ]; then echo "Workflow template errored successfully"; else exit 1; fi
+
+      - name: launch a workflow
+        run: |
+          kubectl apply -f config/samples/workflow/tower_v1alpha1_ansibleworkflow-broken.yaml -n awx
+          kubectl apply -f config/samples/workflow/tower_v1alpha1_ansibleworkflow.yaml -n awx
+          kubectl wait ansibleworkflow -n awx workflow --for condition=Successful=True --timeout=240s
+          kubectl wait ansibleworkflow -n awx broken --for condition=Successful=True --timeout=240s
 
       - name: define a credential
         run: |
@@ -204,20 +217,10 @@ jobs:
           kubectl apply -f config/samples/tower_v1alpha1_ansibleinstancegroup.yaml -n awx
           kubectl wait ansibleinstancegroup -n awx kuber-instance-group --for condition=Successful=True --timeout=240s
 
-      - name: define a workflow template
+      - name: validate error message
         run: |
-          kubectl apply -f config/samples/workflowtemplate/tower_v1alpha1_workflowtemplate-broken.yaml -n awx
-          kubectl apply -f config/samples/workflowtemplate/tower_v1alpha1_workflowtemplate.yaml -n awx
-          kubectl wait workflowtemplate -n awx workflowtemplate-sample --for condition=Successful=True --timeout=240s
-          kubectl wait workflowtemplate -n awx workflowtemplate-broken --for condition=Successful=True --timeout=240s
-          if [ `kubectl get -n awx workflowtemplate workflowtemplate-broken --output="jsonpath={.status.error}"` ]; then echo "Workflow template errored successfully"; else exit 1; fi
-
-      - name: launch a workflow
-        run: |
-          kubectl apply -f config/samples/workflow/tower_v1alpha1_ansibleworkflow-broken.yaml -n awx
-          kubectl apply -f config/samples/workflow/tower_v1alpha1_ansibleworkflow.yaml -n awx
-          kubectl wait ansibleworkflow -n awx workflow --for condition=Successful=True --timeout=240s
-          kubectl wait ansibleworkflow -n awx broken --for condition=Successful=True --timeout=240s
+          if [[ $(kubectl get ansiblejob -n awx broke-job -o jsonpath={.status.error_message}) ]]; then echo "Job errored correctly"; else exit 1 ;fi
+          if [[ $(kubectl get ansibleworkflow -n awx broken -o jsonpath={.status.error_message}) ]]; then echo "Workflow errored correctly"; else exit 1 ;fi
 
       - name: dump logs
         if: always()
